version: '3.7'

services:
  api:
    build:
      context: "./api"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks: 
      - apinet

  dataservice:
    build:
      context: "./dataservice"
      dockerfile: Dockerfile
    networks: 
      - dbnet
      - apinet

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./db/create_table.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks: 
      - dbnet
    
volumes:
  mysql-volume:

networks:
  dbnet:
    name: db_network
  apinet:
    name: api_network
